#!/usr/bin/env zsh

if [[ -z $STOW_FOLDERS ]]; then
  STOW_FOLDERS="aerospace,bin,ghostty,mise,nvim,opencode,tmux,zsh"
fi

if [[ -z $DOTFILES ]]; then
  DOTFILES=$HOME/Code/.dotfiles
fi

pushd $DOTFILES
for folder in $(echo $STOW_FOLDERS | sed "s/,/ /g"); do
  stow --delete $folder
  stow --target=$HOME $folder
done
popd

