[tools]
usage = "latest"
node = "22"
sbt = "latest"
java = "corretto-17"
yarn = "latest"
"npm:brighterscript" = "latest"
rust = "latest"
"npm:prettier" = "latest"
"npm:aws-cdk" = "latest"
stylua = "latest"
"npm:opencode-ai" = "latest"
"cargo:parqeye" = "latest"
neovim = "latest"
"github:junegunn/fzf" = "latest"
tmux = "latest"
aws-cli = { version = "latest", symlink_bins = "true" }
gh = "latest"
lazygit = "latest"
coursier = "latest"
ripgrep = "latest"
"npm:claude" = "latest"
python = "3.13"
"npm:@mariozechner/pi-coding-agent" = "latest"
go = "latest"
bun = "latest"
vault = "latest"
"npm:@github/copilot" = "latest"
stern = "latest"
"npm:autohand-cli" = "latest"
"npm:aws-cdk-local" = "latest"
"npm:dmux" = "latest"
yazi = "latest"
"npm:@openai/codex" = "latest"
"cargo:workmux" = "latest"
"cargo:pertmux" = "latest"
"cargo:worktrunk" = "latest"
"npm:cline" = "latest"
"npm:gsd-pi" = "latest"
"npm:worktale" = "latest"

[settings]
experimental = true
