return {}
-- return {
-- 	"folke/noice.nvim",
-- 	event = "VeryLazy",
-- 	dependencies = {
-- 		"MunifTanjim/nui.nvim",
-- 		"rcarriga/nvim-notify",
-- 	},
-- 	opts = {
-- 		lsp = {
-- 			override = {
-- 				["vim.lsp.util.convert_input_to_markdown_lines"] = true,
-- 				["vim.lsp.util.stylize_markdown"] = true,
-- 				["cmp.entry.get_documentation"] = true,
-- 			},
-- 			signature = {
-- 				enabled = true,
-- 				auto_open = {
-- 					enabled = true,
-- 					trigger = true,
-- 					luasnip = true,
-- 					throttle = 50,
-- 				},
-- 			},
-- 		},
-- 		views = {
-- 			hover = {
-- 				border = {
-- 					style = "rounded",
-- 					padding = { 0, 1 },
-- 				},
-- 				position = {
-- 					row = 2,
-- 				},
-- 				win_options = {
-- 					winhighlight = {
-- 						FloatBorder = "NoiceBorder",
-- 					},
-- 				},
-- 			},
-- 		},
-- 		routes = {
-- 			-- Skip ruler messages (file position notifications)
-- 			{
-- 				filter = {
-- 					event = "msg_show",
-- 					any = {
-- 						{ find = " lines --" },
-- 						{ find = " 1 line --" },
-- 						{ find = "%dL, %d+B" },
-- 					},
-- 				},
-- 				opts = { skip = true },
-- 			},
-- 			-- Skip show mode messages
-- 			{
-- 				filter = {
-- 					event = "msg_showmode",
-- 				},
-- 				opts = { skip = true },
-- 			},
-- 		},
-- 		presets = {
-- 			bottom_search = true,
-- 			command_palette = true,
-- 			long_message_to_split = true,
-- 		},
-- 	},
--   -- stylua: ignore
--   keys = {
--     { "<leader>sn", "", desc = "+noice"},
--     { "<S-Enter>", function() require("noice").redirect(vim.fn.getcmdline()) end, mode = "c", desc = "Redirect Cmdline" },
--     { "<leader>snl", function() require("noice").cmd("last") end, desc = "Noice Last Message" },
--     { "<leader>snh", function() require("noice").cmd("history") end, desc = "Noice History" },
--     { "<leader>sna", function() require("noice").cmd("all") end, desc = "Noice All" },
--     { "<leader>snd", function() require("noice").cmd("dismiss") end, desc = "Dismiss All" },
--     { "<leader>snt", function() require("noice").cmd("pick") end, desc = "Noice Picker (Telescope/FzfLua)" },
--     { "<c-f>", function() if not require("noice.lsp").scroll(4) then return "<c-f>" end end, silent = true, expr = true, desc = "Scroll Forward", mode = {"i", "n", "s"} },
--     { "<c-b>", function() if not require("noice.lsp").scroll(-4) then return "<c-b>" end end, silent = true, expr = true, desc = "Scroll Backward", mode = {"i", "n", "s"}},
--   },
-- 	config = function(_, opts)
-- 		-- HACK: noice shows messages from before it was enabled,
-- 		-- but this is not ideal when Lazy is installing plugins,
-- 		-- so clear the messages in this case.
-- 		if vim.o.filetype == "lazy" then
-- 			vim.cmd([[messages clear]])
-- 		end
-- 		require("noice").setup(opts)
-- 		-- Set white border for signature help
-- 		vim.api.nvim_set_hl(0, "NoiceBorder", { fg = "#ffffff" })
-- 	end,
-- }
